webcam_node:
  ros__parameters:
    cameras:
      - id: 0
        name: "front"
        width: 1280
        height: 720
        fps: 30
        serial_number: "187C02F5"   # udevadm info /dev/video0 | grep ID_SERIAL_SHORT
      # - id: 1
      #   name: "side"
      #   width: 640
      #   height: 480
      #   fps: 30
      #   serial_number: "187C02F5"   # udevadm info /dev/video1 | grep ID_SERIAL_SHORT